import women1 from '../Assets/women1.png'
import women2 from '../Assets/women2.png'
let all_product=[
    {
        id: 1,
        name: 'Camenia',
        image: women1,
        new_price: 25.99,
        old_price: 35.99,
        category: 'women',
      },
      {
        id: 2,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'men',
      },
      {
        id: 3,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 4,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 5,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'kids',
      },
      {
        id: 5,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'men',
      },
      {
        id: 6,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'kids',
      },
      {
        id: 7,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 8,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 9,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 10,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 11,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 12,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 13,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 14,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id:15,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 16,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 17,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 18,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 19,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 20,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 21,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 22,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 23,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 24,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 25,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 26,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 27,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 28,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 29,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 30,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 31,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 32,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 33,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 34,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
      {
        id: 35,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      },
        {
        id: 36,
        name: 'Limini',
        image: women2,
        new_price: 19.99,
        old_price: 27.99,
        category: 'women',
      }
]
export default all_product;